#!/bin/bash
#TODO: figure out better way of adding these deps to class path
cp /usr/share/java/drmaa.jar lib/
cp /usr/share/java/jgdi.jar lib/
cp /usr/share/java/juti.jar lib/
SGE_ROOT=/var/lib/gridengine SGE_CELL=default $*
